-- 0065 — THE THIRD KIND OF QUOTE TAKES ITS RECALL LOG WITH IT TOO.
--
-- 0064 GAVE `item_recalls` TWO DELETE TRIGGERS, for annotations and dialogues,
-- copying the pair 0015 wrote for `item_reviews`. That pair is what `item_reviews`
-- has, and it was the wrong thing to copy: the review deck has THREE sources.
-- `utteranceSource()` in `review_handlers.go` returns `kind: kindUtterance`, and
-- `reviewJoin` builds `item_reviews r ON r.kind = '<that kind>'` — so a standalone
-- quote (a speech, a letter, a proverb) has a schedule row like any other card,
-- and now a recall log too. `item_reviews.kind`'s own comment says `'book' |
-- 'screen'` and has been out of date since 0026 added the third table.
--
-- WHY THIS IS ITS OWN MIGRATION AND NOT AN EDIT TO 0064. Migrations are
-- forward-only. 0064 is already on the branch the owner runs on their phone, so
-- their database has applied it — editing the file would leave the trigger out of
-- every database that had already seen it, which is the failure mode the rule
-- exists to prevent. One more file is the whole cost of getting this right.
--
-- CORRECTION, AND IT IS THE WHOLE REASON THIS FILE EXISTS. The paragraph that
-- stood here claimed `item_reviews` has no utterance trigger, deliberately,
-- because "0026 gave utterances an id FLOOR, so a deleted one's rowid is never
-- reused". BOTH HALVES WERE FALSE, and 0026 says so in as many words:
--
--   "id is a plain INTEGER PRIMARY KEY, so SQLite REUSES a rowid once the
--    highest row is deleted: an orphaned schedule row left behind by a deleted
--    utterance would be silently adopted by the next one created, which would
--    arrive carrying a stranger's stability, review count and lapse history."
--
-- — and then creates `item_reviews_utterance_del`. All THREE of that table's
-- triggers have existed since 0026; the live schema carries them.
--
-- SO THIS IS NOT A JUDGEMENT CALL ABOUT WEIGHT, IT IS 0064 MISSING A COPY. 0064
-- set out to mirror `item_reviews`' triggers and took two of the three that were
-- there. The reason the third matters is 0026's own and needs no restating: a
-- rowid IS reused, so an orphaned row is adopted by the next quote created — and
-- for the log that means somebody else's answers, in a table that grows one row
-- per answer and travels in every backup because it is in `accountTables`.
--
-- The SQL below is unchanged from the version that shipped. Only this comment was
-- corrected, because a shipped migration justifying itself with a false statement
-- about another migration is worse to leave than to touch: the next reader of this
-- file would have believed it.
CREATE TRIGGER item_recalls_utterance_del AFTER DELETE ON utterances BEGIN
  DELETE FROM item_recalls WHERE kind = 'utterance' AND item_id = OLD.id;
END;
