#!/usr/bin/env node
// iso6393-data.mjs — writes the ISO 639-3 registry the Languages section links to.
//
// WHY A GENERATED FILE AND NOT A RUNTIME DEPENDENCY. The registry is SIL's list of
// every language with a three-letter code — 7,800-odd rows — and the app needs two
// things from it: the whole list, searched when a reader adds or links a language,
// and the 639-1 → 639-3 pairs, so a language the app already knows by its two-letter
// code shows its registry code without that search. Importing the package would put
// its whole object graph (every alias, every 639-2 code) into the bundle; this keeps
// the three columns the screen reads, as one string a lazy chunk can carry.
//
// THE SOURCE is the `iso-639-3` npm package (MIT, built from SIL's published
// tables), pinned in web/frontend's devDependencies. `--check` fails when the
// committed files differ from what the pinned package produces, so a bumped
// package cannot ship with a stale table.
//
// Usage:  node scripts/iso6393-data.mjs [--check]

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'web/frontend/src')
const PKG = join(ROOT, 'web/frontend/node_modules/iso-639-3')

const { iso6393 } = await import(join(PKG, 'index.js'))
const version = JSON.parse(readFileSync(join(PKG, 'package.json'), 'utf8')).version

// SPECIAL CODES ARE LEFT OUT. `mis`, `mul`, `und` and `zxx` say "uncoded",
// "several", "undetermined" and "no language" — true things to say in a catalogue
// record and not languages a reader adds to a list of the ones their quotes are in.
const TYPE = { living: 'L', extinct: 'E', ancient: 'A', historical: 'H', constructed: 'C' }
const rows = iso6393
  .filter((l) => TYPE[l.type])
  .sort((a, b) => a.iso6393.localeCompare(b.iso6393))

const table = rows.map((l) => `${l.iso6393}\t${l.name}\t${TYPE[l.type]}${l.scope === 'macrolanguage' ? 'M' : ''}`).join('\n')
const pairs = Object.fromEntries(rows.filter((l) => l.iso6391).map((l) => [l.iso6391, l.iso6393]))

const header = (what) => `// GENERATED by scripts/iso6393-data.mjs from iso-639-3@${version} — do not edit.\n// ${what}\n`

const files = {
  // THE WHOLE REGISTRY, loaded only when a reader opens the language search: one
  // row per code, "code<TAB>reference name<TAB>type", type L living, E extinct,
  // A ancient, H historical, C constructed, with M appended for a macrolanguage.
  'iso6393.data.js':
    header(`ISO 639-3: ${rows.length} codes. Loaded lazily; see iso6393.js.`) +
    `export const ISO6393_TABLE = ${JSON.stringify(table)}\n`,
  // THE SMALL HALF, which is synchronous: every 639-1 code and its 639-3 twin.
  'iso6393.pairs.js':
    header(`ISO 639-1 → ISO 639-3, ${Object.keys(pairs).length} pairs.`) +
    `export const ISO6391_TO_6393 = ${JSON.stringify(pairs, null, 0)}\n`,
}

const check = process.argv.includes('--check')
let stale = 0
for (const [name, body] of Object.entries(files)) {
  const path = join(SRC, name)
  if (check) {
    let cur = ''
    try { cur = readFileSync(path, 'utf8') } catch { /* missing is stale */ }
    if (cur !== body) { console.error(`${name} is stale — run node scripts/iso6393-data.mjs`); stale++ }
  } else {
    writeFileSync(path, body)
  }
}
if (check && stale) process.exit(1)
console.log(check ? `iso6393: up to date — ${rows.length} codes` : `iso6393: wrote ${rows.length} codes, ${Object.keys(pairs).length} pairs`)
