#!/usr/bin/env node
// Writes docs/data/tracker.json from the issue tracker, so that the roadmap generator
// needs no network access and the page can be rebuilt from the repo alone.
//
// Run by .github/workflows/roadmap-bugs.yml on every issue event. Runs locally too, if
// you have `gh` and are logged in — useful for seeing what the page will say before it
// says it:
//
//   node scripts/roadmap-tracker.mjs && node scripts/roadmap-data.mjs
//
// It collects two things and nothing else:
//
//   open_bugs  every OPEN issue labelled `bug`, with the body the form built.
//   closed     of the issue numbers referenced from docs/data/*.json, the ones that are
//              closed. Only referenced numbers are queried — the whole closed history is
//              neither needed nor cheap, and this is what lets a shipped feature drop
//              itself off the page.
//
// Pull requests are filtered out: /issues returns them too, and a PR titled like a fix
// is not a bug report.

import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'docs', 'data', 'tracker.json')
const REPO = process.env.GITHUB_REPOSITORY || 'aaronified/tippani'

function gh(args) {
  try {
    return execFileSync('gh', args, { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 })
  } catch (e) {
    const why = (e.stderr || e.message || '').trim()
    console.error(`gh failed: ${args.join(' ')}\n${why}`)
    if (/not found|ENOENT/i.test(why)) console.error('install the GitHub CLI, or run this in Actions where it is preinstalled')
    if (/auth|credential/i.test(why)) console.error('run `gh auth login`, or set GH_TOKEN')
    process.exit(1)
  }
}

// `gh api --paginate --jq` streams one JSON object per line, which is the only shape of
// paginated output that stays parseable across gh versions.
const ndjson = (out) =>
  out
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => JSON.parse(l))

const openBugs = ndjson(
  gh([
    'api',
    '--paginate',
    '-H', 'Accept: application/vnd.github+json',
    `repos/${REPO}/issues?state=open&labels=bug&per_page=100&sort=created&direction=asc`,
    '--jq',
    '.[] | select(has("pull_request") | not) | {number, title, body, url: .html_url, created_at, user: .user.login}',
  ]),
)

// Which numbers do the hand-written files point at? Those are the only ones whose closed
// state can change what the page shows.
const readJSON = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'))
const bugs = readJSON('docs/data/bugs.json')
const feats = readJSON('docs/data/features.json')

const referenced = new Set(
  [
    ...(bugs.manual ?? []).map((b) => b.issue),
    ...Object.keys(bugs.overrides ?? {}),
    ...(feats.accepted ?? []).map((f) => f.issue),
    ...(feats.considered ?? []).map((f) => f.issue),
  ]
    .map(Number)
    .filter((n) => Number.isInteger(n) && n > 0),
)

const closed = []
for (const n of [...referenced].sort((x, y) => x - y)) {
  let state
  try {
    state = JSON.parse(gh(['api', `repos/${REPO}/issues/${n}`, '--jq', '{state: .state}'])).state
  } catch {
    console.error(`could not read issue #${n} — treating it as open`)
    continue
  }
  if (state === 'closed') closed.push(n)
}

// Preserve the header comment: it is the only documentation a generated file gets.
const previous = (() => {
  try {
    return readJSON('docs/data/tracker.json')
  } catch {
    return {}
  }
})()

// Only re-stamp `generated` when the tracker state actually moved. Otherwise every issue
// event — a comment, a label edit, an assignment — rewrites the timestamp, the workflow
// sees a changed file and commits, and the history fills with commits that say nothing.
// Two label edits produced three of those before this existed.
const same =
  JSON.stringify(previous.open_bugs ?? null) === JSON.stringify(openBugs) &&
  JSON.stringify(previous.closed ?? null) === JSON.stringify(closed)

writeFileSync(
  OUT,
  JSON.stringify(
    {
      _: previous._ ?? ['GENERATED by scripts/roadmap-tracker.mjs. Do not edit.'],
      generated: same ? (previous.generated ?? null) : new Date().toISOString(),
      open_bugs: openBugs,
      closed,
    },
    null,
    2,
  ) + '\n',
)

console.log(
  `tracker.json: ${openBugs.length} open bug(s), ${closed.length} closed of ${referenced.size} referenced` +
    (same ? ' — unchanged, timestamp kept' : ' — state moved'),
)
