#!/usr/bin/env node
// Renders docs/data/*.json into the marked regions of docs/roadmap.html.
//
// The roadmap is a hand-written, self-contained page with no script in it, so the
// generated parts are baked in at commit time rather than fetched at view time. That is
// the whole reason this file exists.
//
// THREE DATA FILES, and which of them is yours matters:
//
//   docs/data/tracker.json   GENERATED by .github/workflows/roadmap-bugs.yml. The issue
//                            tracker's state — open `bug` issues, and every closed issue
//                            number. Never edit it.
//   docs/data/bugs.json      YOURS. Hand-written bugs, plus `overrides` that correct any
//                            generated entry by issue number.
//   docs/data/features.json  YOURS. Accepted and considered feature requests. Nothing
//                            automated writes here: accepting a request is a decision.
//
// TWO RULES THAT DO THE BOOKKEEPING FOR YOU:
//
//   Anything carrying an `issue` number stops rendering once that issue is closed. Fix
//   the bug or ship the feature, close the issue, and the roadmap catches up by itself.
//   A `fixed_in` / `shipped_in` version does the same for items that were never issues.
//
//   A generated entry is a starting point, not a verdict. `overrides` in bugs.json wins
//   over whatever the reporter wrote, and the workflow cannot touch it.
//
// SIX REGIONS, each delimited by <!-- ROADMAP:<NAME>:START --> / :END -->
//
//   BUGS  RAIL_BUGS              bugs.json manual[] + tracker.json open_bugs[]
//   FEATURES  RAIL_FEATURES      features.json accepted[]
//   CONSIDERED  RAIL_CONSIDERED  features.json considered[], appended to Later / maybe
//
// Everything outside the markers is left byte-for-byte alone.
//
// SAFETY, because a workflow that can rewrite a published page can also ruin one:
//
//   Every write first copies the current page to docs/roadmap.backup.html — the last
//   known-good version, committed alongside. `--restore` puts it back.
//   Nothing is written unless the rendered page still passes verify(): all twelve
//   markers intact, the page structure intact, and no implausible collapse in size.
//   A failed render leaves the committed page exactly as it was.
//
//   node scripts/roadmap-data.mjs            write (backing up first)
//   node scripts/roadmap-data.mjs --check    fail if the page is out of date (CI uses this)
//   node scripts/roadmap-data.mjs --restore  put the backup back, and stop
//
// No dependencies, and none wanted: it runs on a bare `node` in a workflow container.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PAGE = join(ROOT, 'docs', 'roadmap.html')
const BACKUP = join(ROOT, 'docs', 'roadmap.backup.html')
const REPO = 'aaronified/tippani'
const CHECK = process.argv.includes('--check')
const RESTORE = process.argv.includes('--restore')

const REGIONS = ['BUGS', 'RAIL_BUGS', 'FEATURES', 'RAIL_FEATURES', 'CONSIDERED', 'RAIL_CONSIDERED']

if (RESTORE) {
  if (!existsSync(BACKUP)) {
    console.error('no docs/roadmap.backup.html to restore from')
    process.exit(1)
  }
  writeFileSync(PAGE, readFileSync(BACKUP, 'utf8'))
  console.log('docs/roadmap.html restored from docs/roadmap.backup.html')
  process.exit(0)
}

// The bug form's field labels, as GitHub renders them into the issue body ("### Label").
// Renaming one in .github/ISSUE_TEMPLATE/bug_report.yml means changing it here too.
const FIELD = {
  what: 'What happens',
  expected: 'What you expected instead',
  steps: 'Steps to reproduce',
  version: 'Version',
  deployment: 'How you are running it',
  environment: 'Browser and OS',
}

const esc = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

// Straight quotes read as sloppy beside the hand-written prose, so pulled-in text gets
// the same typography as everything else on the page.
const typo = (s) =>
  String(s ?? '')
    .replace(/(\w)'(\w)/g, '$1’$2')
    .replace(/(^|[\s(])"/g, '$1“')
    .replace(/"/g, '”')
    .replace(/ -- /g, ' — ')

const slug = (s) =>
  String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48)

const issueURL = (n) => `https://github.com/${REPO}/issues/${n}`

// A form-built issue body is a flat list of "### Label\n\nvalue" blocks. Pull one out by
// label. Returns '' for a missing field and for the "_No response_" GitHub writes when
// an optional field was left blank.
function field(body, label) {
  const lines = String(body ?? '').replace(/\r\n/g, '\n').split('\n')
  const at = lines.findIndex((l) => l.trim() === `### ${label}`)
  if (at < 0) return ''
  const out = []
  for (const l of lines.slice(at + 1)) {
    if (l.startsWith('### ')) break
    out.push(l)
  }
  const v = out.join('\n').trim()
  return /^_No response_\.?$/.test(v) ? '' : v
}

// Deliberately NOT a Markdown renderer. Issue bodies are untrusted text going into a page
// I publish, so everything is escaped first and only paragraphs, list items and `code`
// spans are recognised. An issue cannot inject markup here, and fenced code blocks are
// dropped rather than rendered — a stack trace belongs on the issue, not on the roadmap.
function prose(md, { indent = '  ' } = {}) {
  const inline = (t) => esc(typo(t)).replace(/`([^`]+)`/g, '<code>$1</code>')
  const blocks = String(md ?? '')
    .replace(/\r\n/g, '\n')
    .replace(/```[\s\S]*?```/g, '')
    .split(/\n{2,}/)
    .map((b) => b.trim())
    .filter(Boolean)

  const out = []
  for (const b of blocks) {
    const lines = b.split('\n').map((l) => l.trim()).filter(Boolean)
    if (!lines.length) continue
    if (lines.every((l) => /^([-*+]|\d+[.)])\s+/.test(l))) {
      const tag = /^\d+[.)]\s+/.test(lines[0]) ? 'ol' : 'ul'
      out.push(`${indent}<${tag}>`)
      for (const l of lines) out.push(`${indent}  <li>${inline(l.replace(/^([-*+]|\d+[.)])\s+/, ''))}</li>`)
      out.push(`${indent}</${tag}>`)
    } else {
      out.push(`${indent}<p>${inline(lines.join(' '))}</p>`)
    }
  }
  return out
}

// "[bug]: thing is broken" -> "Thing is broken". The form pre-fills that prefix; it is
// triage furniture and has no business in a heading.
function heading(title) {
  const t = String(title ?? '')
    .replace(/^\s*[[(]?\s*(bug|feature|fix|bugfix|request)\s*[\])]?\s*:?\s*/i, '')
    .trim()
  return t ? t[0].toUpperCase() + t.slice(1) : 'Untitled'
}

const body = (lines, indent) => (lines ?? []).map((l) => (l.trim() ? indent + l : l))

// Whatever the page already uses. Checked out CRLF on Windows and LF on the Actions
// runner, and splicing the wrong one would rewrite every generated line on every
// platform switch — a diff that says nothing, committed by a bot, forever.
let EOL = '\n'

function region(html, name, lines) {
  const start = `<!-- ROADMAP:${name}:START -->`
  const end = `<!-- ROADMAP:${name}:END -->`
  const i = html.indexOf(start)
  const j = html.indexOf(end)
  if (i < 0 || j < 0 || j < i) throw new Error(`missing or inverted ROADMAP:${name} markers in docs/roadmap.html`)
  // Indent the END marker to match START, so a generated region still reads as
  // hand-written HTML. It has to come from START: the whitespace that used to precede
  // END is inside the region, so the first render eats it and every later render would
  // then measure zero.
  const pad = (html.slice(0, i).match(/\n([ \t]*)$/) ?? [, ''])[1]
  const inner = lines.length ? EOL + lines.join(EOL) + EOL : EOL
  return html.slice(0, i + start.length) + inner + pad + html.slice(j)
}

const railLinks = (items, indent) =>
  items.map(({ id, label }) => `${indent}<li><a href="#${esc(id)}">${esc(typo(label))}</a></li>`)

// Six spaces: the rail's marked regions sit inside a <details class="grp">, one level in
// from where they started.
const railList = (items, { indent = '      ', empty } = {}) =>
  items.length
    ? [`${indent}<ul class="sub">`, ...railLinks(items, `${indent}  `), `${indent}</ul>`]
    : [`${indent}<ul class="sub">`, `${indent}  <li><a href="#${empty.id}">${esc(empty.label)}</a></li>`, `${indent}</ul>`]

// The provenance line under a generated heading.
function meta(bits) {
  return bits.length ? [`  <p class="mono issue-meta">${bits.join(' · ')}</p>`] : []
}

// ---- bugs -------------------------------------------------------------------------

function bugs(hand, tracker) {
  const closed = new Set((tracker.closed ?? []).map(Number))
  const overrides = hand.overrides ?? {}
  const cards = []
  const rail = []
  const dropped = []
  // Issue numbers a hand-written entry already speaks for. Both halves of the list read
  // from the same tracker, so without this a bug I wrote up AND filed appears twice —
  // once in my words, once in the form's. Mine wins; the issue still governs whether it
  // appears at all.
  const claimed = new Set(
    (hand.manual ?? []).map((b) => Number(b.issue)).filter((n) => Number.isInteger(n) && n > 0),
  )

  for (const b of hand.manual ?? []) {
    if (b.fixed_in) { dropped.push(`${b.id || slug(b.title)} (fixed in ${b.fixed_in})`); continue }
    if (b.issue && closed.has(Number(b.issue))) { dropped.push(`${b.id} (#${b.issue} closed)`); continue }
    const id = b.id || `bug-${slug(b.title)}`
    rail.push({ id, label: b.railLabel || heading(b.title) })
    cards.push(`<div class="card bug" id="${esc(id)}">`)
    cards.push(`  <h3>${esc(typo(heading(b.title)))}</h3>`)
    cards.push(...meta(b.issue ? [`<a href="${issueURL(b.issue)}">#${b.issue}</a>`] : []))
    cards.push(...body(b.html, '  '))
    cards.push('</div>', '')
  }

  for (const i of tracker.open_bugs ?? []) {
    const n = Number(i.number)
    if (closed.has(n)) continue                       // belt and braces; open_bugs should be open
    if (claimed.has(n)) continue                      // a manual entry is already telling this one
    const o = overrides[String(n)] ?? {}
    if (o.hide) { dropped.push(`#${n} (hidden by override)`); continue }

    const id = `bug-${n}`
    const title = heading(o.title ?? i.title)
    rail.push({ id, label: o.railLabel || title })

    cards.push(`<div class="card bug" id="${esc(id)}">`)
    cards.push(`  <h3>${esc(typo(title))}</h3>`)

    const bits = [`<a href="${esc(i.url || issueURL(n))}">#${n}</a>`]
    const ver = field(i.body, FIELD.version)
    const dep = field(i.body, FIELD.deployment)
    const env = field(i.body, FIELD.environment)
    if (ver) bits.push(`reported on ${esc(ver)}`)
    if (dep) bits.push(esc(dep.toLowerCase()))
    if (env) bits.push(esc(env))
    cards.push(...meta(bits))

    if (o.html) {
      cards.push(...body(o.html, '  '))
    } else {
      const what = field(i.body, FIELD.what)
      const expected = field(i.body, FIELD.expected)
      const steps = field(i.body, FIELD.steps)
      if (what) cards.push(...prose(what))
      if (expected) cards.push(...prose(`Expected instead: ${expected}`))
      if (!what && !expected) cards.push(`  <p>No description was filed — see <a href="${esc(i.url || issueURL(n))}">#${n}</a>.</p>`)
      if (steps) {
        cards.push('  <details class="repro">', '    <summary>Steps to reproduce</summary>')
        cards.push(...prose(steps, { indent: '    ' }))
        cards.push('  </details>')
      }
      if (o.note) cards.push(...prose(o.note))
    }
    cards.push('</div>', '')
  }

  while (cards.length && !cards[cards.length - 1]) cards.pop()
  return { cards, rail, dropped }
}

// ---- features ---------------------------------------------------------------------

function provenance(f) {
  const bits = []
  if (f.issue) bits.push(`<a href="${issueURL(f.issue)}">#${f.issue}</a>`)
  if (f.credit) bits.push(`asked for by <a href="https://github.com/${esc(f.credit)}">@${esc(f.credit)}</a>`)
  if (f.near) bits.push(`sits beside ${esc(typo(f.near))}`)
  return bits
}

// Shared drop rule: shipped, or its issue is closed.
function live(list, closed, dropped) {
  return (list ?? []).filter((f) => {
    const id = f.id || slug(f.title)
    if (f.shipped_in) { dropped.push(`${id} (shipped in ${f.shipped_in})`); return false }
    if (f.issue && closed.has(Number(f.issue))) { dropped.push(`${id} (#${f.issue} closed)`); return false }
    return true
  })
}

function accepted(list) {
  const cards = []
  const rail = []
  for (const f of list) {
    const id = f.id || `req-${slug(f.title)}`
    rail.push({ id, label: f.railLabel || heading(f.title) })
    cards.push(`<div class="card req" id="${esc(id)}">`)
    cards.push(`  <h3>${esc(typo(heading(f.title)))}</h3>`)
    cards.push(...meta(provenance(f)))
    cards.push(...body(f.html, '  '))
    cards.push('</div>', '')
  }
  while (cards.length && !cards[cards.length - 1]) cards.pop()
  return { cards, rail }
}

function considered(list) {
  const items = []
  const rail = []
  for (const f of list) {
    const id = f.id || `req-${slug(f.title)}`
    rail.push({ id, label: f.railLabel || heading(f.title) })
    items.push(`  <li id="${esc(id)}">`)
    items.push(`    <strong>${esc(typo(heading(f.title)))}</strong>`)
    items.push(...body(f.html, '    '))
    const bits = provenance(f)
    if (bits.length) items.push(`    <br><span class="mono issue-meta">${bits.join(' · ')}</span>`)
    items.push('  </li>')
  }
  return { items, rail }
}

// ---- go ---------------------------------------------------------------------------

const readJSON = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'))
const readJSONIfAny = (p) => (existsSync(join(ROOT, p)) ? readJSON(p) : null)

// Each numbered section carries a fill point in its <summary>. Put the section's issue
// number in it, so the page and the tracker point at each other. Idempotent: it matches
// an already-filled link as readily as an empty span, and an unmapped section renders as
// nothing at all rather than as a dead "#".
function sectionIssues(html, map) {
  const sections = map?.sections ?? {}
  let filled = 0
  const out = html.replace(
    /<(span|a)([^>]*?)class="sec-issue"([^>]*?)data-for="(s\d+)"([^>]*?)>[\s\S]*?<\/\1>/g,
    (_all, _tag, _a, _b, id) => {
      const n = sections[id]
      if (!n) return `<span class="sec-issue" data-for="${id}"></span>`
      filled++
      return `<a class="sec-issue" data-for="${id}" href="${issueURL(n)}" title="Track ${id} on the issue tracker">#${n}</a>`
    },
  )
  return { html: out, filled }
}

const hand = readJSON('docs/data/bugs.json')
const feats = readJSON('docs/data/features.json')
const tracker = readJSON('docs/data/tracker.json')
const closedSet = new Set((tracker.closed ?? []).map(Number))
const dropped = []

const b = bugs(hand, tracker)
dropped.push(...b.dropped)
const a = accepted(live(feats.accepted, closedSet, dropped))
const c = considered(live(feats.considered, closedSet, dropped))

const before = readFileSync(PAGE, 'utf8')
// Match the page's own line endings before splicing anything into it.
EOL = before.includes('\r\n') ? '\r\n' : '\n'
let html = before

html = region(html, 'BUGS', b.cards.length ? b.cards : ['<p class="mono">Nothing open. That will not last.</p>'])
html = region(html, 'RAIL_BUGS', railList(b.rail, { empty: { id: 'bugs', label: 'Nothing open' } }))
html = region(
  html,
  'FEATURES',
  a.cards.length ? a.cards : ['<p class="mono">Nothing accepted yet — the list starts with the first request I say yes to.</p>'],
)
html = region(html, 'RAIL_FEATURES', railList(a.rail, { empty: { id: 'requests', label: 'Nothing accepted yet' } }))
html = region(html, 'CONSIDERED', c.items)
html = region(html, 'RAIL_CONSIDERED', railLinks(c.rail, '        '))

const secs = sectionIssues(html, readJSONIfAny('docs/data/issue-map.json'))
html = secs.html

const counts = `${b.rail.length} bug(s), ${a.rail.length} accepted, ${c.rail.length} considered, ${secs.filled}/25 sections linked`
for (const d of dropped) console.log(`dropped: ${d}`)

// Refuse to publish a page that no longer looks like the page. Cheap, and it is the
// difference between a bad render being a failed job and a bad render being live.
function verify(out, prev) {
  const bad = []
  for (const r of REGIONS) {
    if (!out.includes(`<!-- ROADMAP:${r}:START -->`)) bad.push(`lost the ROADMAP:${r}:START marker`)
    if (!out.includes(`<!-- ROADMAP:${r}:END -->`)) bad.push(`lost the ROADMAP:${r}:END marker`)
  }
  for (const need of ['</main>', '</body>', 'id="backlog"', 'id="later"', 'class="rail"', 'id="s25"']) {
    if (!out.includes(need)) bad.push(`lost ${need}`)
  }
  // The generated regions are a small fraction of the page; a large shrink means
  // something ate prose it had no business touching.
  if (out.length < prev.length * 0.75) bad.push(`shrank from ${prev.length} to ${out.length} bytes`)
  // Count real tags only — the stylesheet and the marker comments both talk ABOUT
  // <details>, and prose describing a tag is not a tag.
  const markup = out.replace(/<!--[\s\S]*?-->/g, '').replace(/\/\*[\s\S]*?\*\//g, '')
  const opens = (markup.match(/<details[\s>]/g) ?? []).length
  const closes = (markup.match(/<\/details>/g) ?? []).length
  if (opens !== closes) bad.push(`${opens} <details> against ${closes} </details>`)
  return bad
}

if (CHECK) {
  const bad = verify(html, before)
  if (bad.length) {
    for (const m of bad) console.error(`broken render: ${m}`)
    process.exit(1)
  }
  if (html !== before) {
    console.error(`docs/roadmap.html is out of date with docs/data/*.json (${counts}).`)
    console.error('Run: node scripts/roadmap-data.mjs')
    process.exit(1)
  }
  console.log(`up to date — ${counts}`)
} else if (html === before) {
  // Still seed the backup on the first run, so a restore point exists before the
  // automation ever gets a turn.
  if (!existsSync(BACKUP)) {
    writeFileSync(BACKUP, before)
    console.log(`no change — ${counts}; wrote the first docs/roadmap.backup.html`)
  } else {
    console.log(`no change — ${counts}`)
  }
} else {
  const bad = verify(html, before)
  if (bad.length) {
    for (const m of bad) console.error(`broken render: ${m}`)
    console.error('docs/roadmap.html left untouched — fix the generator or the data, not the page')
    process.exit(1)
  }
  writeFileSync(BACKUP, before)          // last known good, before we touch the page
  writeFileSync(PAGE, html)
  console.log(`docs/roadmap.html updated — ${counts} (previous kept in docs/roadmap.backup.html)`)
}
