// THE ISO 639-3 REGISTRY — every language with a three-letter code, which is what
// a row in Metadata › Languages is linked to.
//
// WHY 639-3 AND NOT THE LIST iso639.js ALREADY HAS. That file is the languages this
// app knows well enough to OFFER — an autonym it is sure of, a script, a mark — and
// it is ninety-odd rows on purpose. The registry is the answer to a different
// question: "which language, exactly, is this?" Ancient Greek is `grc`, not `el`;
// Sylheti is `syl` and has no two-letter code at all. A reader's list is only as
// precise as the codes behind it, and the two-letter list cannot name most of the
// languages anybody's quotes are in.
//
// TWO HALVES, AND ONLY ONE IS SYNCHRONOUS. The pairs (639-1 → 639-3) are 2KB and
// ship with the app, so a language iso639.js knows shows its code on first paint.
// The table is 150KB and loads the first time somebody searches it — a reader who
// never adds a language never downloads it.
//
// Both files are GENERATED by scripts/iso6393-data.mjs; `--check` guards them.

import { ISO6391_TO_6393 } from './iso6393.pairs.js'
import { languageFor } from './iso639.js'

const THREE = /^[a-z]{3}$/

// iso6393For — the registry code a stored language value resolves to without
// loading anything: the code a reader linked it to, else the one its iso639.js row
// implies. "" when neither knows, which is the honest answer for a language typed
// free and never linked.
export function iso6393For(value, linked = '') {
  const l = String(linked || '').toLowerCase()
  if (THREE.test(l)) return l
  const code = languageFor(value)?.code || ''
  if (THREE.test(code)) return code
  return ISO6391_TO_6393[code] || ''
}

// isISO6393Shape — three lower-case letters. Whether the code exists is the table's
// question; this is only whether it could.
export const isISO6393Shape = (s) => THREE.test(String(s || ''))

// ---- the table, loaded on demand -------------------------------------------

let loading = null
let rows = null
let byCode = null

// loadISO6393 resolves to the parsed registry, fetching it once.
export function loadISO6393() {
  if (rows) return Promise.resolve(rows)
  if (!loading) {
    loading = import('./iso6393.data.js').then(({ ISO6393_TABLE }) => {
      rows = ISO6393_TABLE.split('\n').map((line) => {
        const [code, name, type] = line.split('\t')
        return { code, name, type: type[0], macro: type.includes('M'), fold: fold(name) }
      })
      byCode = new Map(rows.map((r) => [r.code, r]))
      return rows
    })
  }
  return loading
}

// iso6393Name — the reference name for a code once the table is in, else "".
export const iso6393Name = (code) => byCode?.get(String(code || '').toLowerCase())?.name || ''

// Accents off and case down, so "arberesh" finds "Arbëreshë Albanian" and a
// reader does not need the diacritic to find the language that has one.
function fold(s) {
  return String(s || '').normalize('NFD').replace(/\p{M}/gu, '').toLowerCase()
}

// searchISO6393 ranks the registry against what was typed: the exact code first,
// then names starting with it, then a word inside a name starting with it, then a
// name merely containing it. Within a rank, living languages before the rest and
// shorter names first, because "French" is the likelier answer to "fre" than
// "Old French (842–ca. 1400)".
export function searchISO6393(list, query, limit = 40) {
  const q = fold(query).trim()
  if (!q || !list) return []
  const hits = []
  for (const r of list) {
    let rank = -1
    if (r.code === q) rank = 0
    else if (r.fold.startsWith(q)) rank = 1
    else if (r.fold.includes(' ' + q) || r.fold.includes('(' + q) || r.fold.includes('-' + q)) rank = 2
    else if (q.length >= 3 && r.fold.includes(q)) rank = 3
    if (rank >= 0) hits.push([rank, r.type === 'L' ? 0 : 1, r.name.length, r])
  }
  hits.sort((a, b) => a[0] - b[0] || a[1] - b[1] || a[2] - b[2] || a[3].name.localeCompare(b[3].name))
  return hits.slice(0, limit).map((h) => h[3])
}
